name: Check the project versions are the same
description: Check the project versions are the same. Requires libxml2-utils.

runs:
  using: "composite"
  steps:
    - name: Check the version is unique
      shell: bash
      run: |
        versionPath='/Project/PropertyGroup/Version/text()'
        coreVersion=$(xmllint --xpath $versionPath ./FatNetLib.Core/FatNetLib.Core.csproj);
        jsonVersion=$(xmllint --xpath $versionPath ./FatNetLib.Json/FatNetLib.Json.csproj);
        msLogVersion=$(xmllint --xpath $versionPath ./FatNetLib.MicrosoftLogging/FatNetLib.MicrosoftLogging.csproj);
        unityLogVersion=$(xmllint --xpath $versionPath ./FatNetLib.UnityLogging/FatNetLib.UnityLogging.csproj);
        version=$coreVersion
        if [[ $coreVersion != $version || $jsonVersion != $version || $msLogVersion != $version || $unityLogVersion != $version ]]; then
          echo 'Project versions are not the same'
          exit 1
        fi
