name: Check versions are unique and the same in each project
description: Check versions are unique and the same in each project

inputs:
  repo-username:
    description: Repository username
    required: true
  repo-password:
    description: Repository password
    required: true
    
outputs:
  project-version:
    description: "Project version"
    value: ${{ steps.define-project-version.outputs.project-version }}

runs:
  using: "composite"
  steps:
    - name: Install xmllint
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libxml2-utils
      
    - name: Define the project version
      id: define-project-version
      shell: bash
      run: |
        versionXPath='/Project/PropertyGroup/Version/text()';
        version=$(xmllint --xpath $versionXPath FatNetLib.Core/FatNetLib.Core.csproj);
        echo "project-version=$(echo $version)" >> $GITHUB_OUTPUT;

    - name: Check the project versions are the same
      uses: ./.github/actions/check-versions-synchronized

    - name: Check the FatNetLib.Core version is unique
      uses: ./.github/actions/check-version-unique
      with:
        repo-username: ${{ inputs.repo-username }}
        repo-password: ${{ inputs.repo-password }}
        package-name: FatNetLib.Core
        csproj-path: FatNetLib.Core/FatNetLib.Core.csproj

    - name: Check the FatNetLib.Json version is unique
      uses: ./.github/actions/check-version-unique
      with:
        repo-username: ${{ inputs.repo-username }}
        repo-password: ${{ inputs.repo-password }}
        package-name: FatNetLib.Json
        csproj-path: FatNetLib.Json/FatNetLib.Json.csproj

    - name: Check the FatNetLib.MicrosoftLogging version is unique
      uses: ./.github/actions/check-version-unique
      with:
        repo-username: ${{ inputs.repo-username }}
        repo-password: ${{ inputs.repo-password }}
        package-name: FatNetLib.MicrosoftLogging
        csproj-path: FatNetLib.MicrosoftLogging/FatNetLib.MicrosoftLogging.csproj

    - name: Check the FatNetLib.UnityLogging version is unique
      uses: ./.github/actions/check-version-unique
      with:
        repo-username: ${{ inputs.repo-username }}
        repo-password: ${{ inputs.repo-password }}
        package-name: FatNetLib.UnityLogging
        csproj-path: FatNetLib.UnityLogging/FatNetLib.UnityLogging.csproj
